"""Initial schema — created from cockpit.models metadata (ADR-005) + FTS5 index table.

From 0002 onward, migrations are proper autogenerated deltas.
"""

from __future__ import annotations

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from cockpit.models import Base

    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)
    op.execute(
        "CREATE VIRTUAL TABLE IF NOT EXISTS knowledge_fts "
        "USING fts5(workspace_id, path, title, content)"
    )


def downgrade() -> None:
    from cockpit.models import Base

    op.execute("DROP TABLE IF EXISTS knowledge_fts")
    Base.metadata.drop_all(bind=op.get_bind())
